apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "visit-tracker-api.fullname" . }}-config
  labels:
    {{- include "visit-tracker-api.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.appConfig }}
  {{ $key }}: "{{ $value }}"
  {{- end }}