{{- if .Values.secrets.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "visit-tracker-api.fullname" . }}-secret
  labels:
    {{- include "visit-tracker-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.values }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}