apiVersion: v1
kind: Secret
metadata:
  name: {{ include "visit-tracker-api.fullname" . }}-secret
  labels:
    {{- include "visit-tracker-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.appSecrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}