image:
  repository: visit-tracker-api
  tag: dev
  pullPolicy: Never

service:
  type: NodePort
  port: 8000

containerPort: 8000

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /ready
    port: 8000
  initialDelaySeconds: 5
  failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 80

appConfig:
  ENVIRONMENT: development

secrets:
  enabled: true
  values:
    SECRET_KEY: "placeholder-secret-key"
    DATABASE_PASSWORD: "placeholder-db-pass"