name: Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  verify-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Run health check
      run: |
        uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep 5  # Wait for the server to start
        curl -f --retry 3 --retry-delay 1 http://localhost:8000/health

    - name: Shutdown app
      run: pkill uvicorn || true
  
  build-and-test:
    runs-on: ubuntu-latest
    needs: verify-api

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Debug username
      run: echo "DockerHub user is set" && test -n "${{ secrets.DOCKERHUB_USERNAME }}"
    
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/visit-tracker-api:latest .

    - name: Run container
      run: |
        docker run -d -p 8000:8000 --name test-app visit-tracker-api:latest
        sleep 5

    - name: Run health check
      run: |
        curl -f --retry 3 --retry-delay 1 http://localhost:8000/health

    - name: Log in to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag and Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/visit-tracker-api:latest

    - name: Stop and remove container
      run: docker rm -f test-app